[build-system]
requires = ["setuptools"]

[project]
name = "MLPerfTinyTorch"
version = "0.0.1"
authors = [
  { name="Lawrence Quizon", email="lawrence.quizon@eee.upd.edu.ph" },
]
description = "Pytorch Implementations of MLPerfTiny Models"
dependencies = [
    "torch",
]
package_data={'my_pkg' :['my_pkg/resources/nltk_data/*']}
